drop table if exists PROYECTO_USUARIO;
drop table if exists USUARIO_ROLES;
drop table if exists TAREAS;
drop table if exists PROYECTOS;
drop table if exists USUARIOS;

create table USUARIOS (
                          id         bigint generated by default as identity PRIMARY KEY,
                          nombres    varchar(255)                        not null,
                          apellidos  varchar(255)                        not null,
                          username   varchar(255)                        not null unique,
                          email      varchar(255)                        not null unique,
                          password   varchar(255)                        not null,
                          tiempo_proyecto bigint                         not null,
                          is_deleted boolean default false
);

create table USUARIO_ROLES (
                               user_id bigint not null,
                               roles varchar (20) check ( roles in ('supervisor','director','empleado')),
                               FOREIGN KEY (user_id) REFERENCES USUARIOS(id) ON DELETE cascade
);

create table PROYECTOS (
                          id bigint generated by default as identity PRIMARY KEY,
                          nombre varchar(20) not null UNIQUE,
                          descripcion varchar(255) not null,
                          estado varchar(20) check (estado in ('ACTIVO','SUSPENDIDO','COMPLETADO')),
                          is_deleted boolean default false
);

create table PROYECTO_USUARIO(
                            proyecto_id bigint not null,
                            usuario_id bigint not null,
                            PRIMARY KEY (proyecto_id, usuario_id),
                            FOREIGN KEY (proyecto_id) REFERENCES PROYECTOS(id) ON DELETE CASCADE,
                            FOREIGN KEY (usuario_id) REFERENCES USUARIOS(id) ON DELETE CASCADE
);

create table TAREAS (
                           id bigint generated by default as identity PRIMARY KEY,
                           nombre varchar(255) not null,
                           descripcion varchar(255) not null,
                           estado varchar(30) check (estado in ('ACTIVO','COMPLETADO','SUSPENDIDO')),
                           fechaCreacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP not null,
                           usuario_id bigint,
                           FOREIGN KEY (usuario_id) REFERENCES USUARIOS(id) ON DELETE SET NULL
);




