spring.application.name=timescope
server.port=${PORT:8080}
api.version=${API_VERSION:v1}


## Base de datos de desarrollo puede ser H2
# En fichero embebida o en memoria, t� eliges
# spring.datasource.url=jdbc:h2:./tarjetasapirest
spring.datasource.url=jdbc:h2:mem:tarjetasapirest
# Usuario y contraseña de la base de datos
spring.datasource.username=sa
#spring.datasource.password=password
# Habilitamos la consola de H2
# En nuestro caso http://localhost:3000/h2-console
spring.h2.console.enabled=true

## Carga de Base de Datos
# Habilitamos que cargue los datos de prueba en la base de datos
# estos datos los carga del fichero data.sql del directorio resources
spring.jpa.defer-datasource-initialization=true
# Habilitamos la creación de la base de datos en cada arranque
spring.jpa.hibernate.ddl-auto=create-drop
# Habilitamos la carga de datos de prueba en cada arranque
spring.sql.init.mode=always

## SQL
# Habilitamos los mensajes sql en el log para ver las consultas
spring.jpa.show-sql=true
# Formatea la salida SQL para que se lea mejor en la consola
#spring.jpa.properties.hibernate.format_sql=true