spring.application.name=timescope
server.port=${PORT:8080}
api.version=${API_VERSION:v1}

spring.web.error.include-message=always

## Base de datos de desarrollo puede ser H2
#spring.datasource.password=password
# http://localhost:8080/h2-console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.url=jdbc:h2:mem:timescope
spring.datasource.username=sa
spring.h2.console.settings.web-allow-others=false
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

## Carga de Base de Datos
spring.jpa.defer-datasource-initialization=true
spring.jpa.hibernate.ddl-auto=create-drop
spring.sql.init.mode=always
logging.level.org.hibernate.orm.jdbc.bind=TRACE

## SQL
spring.jpa.show-sql=true

## JWT
jwt.secret=SoloEstasYSoloAprendisteAEstarPorVivirConMiedoAVolverAmarOjalaTeQuieranComoQuisiste
jwt.expiration=86400
rutaFront = ${URL:http://localhost:3000/dashboard}
#Email
mailtrap.api.token=04c47e26649608ba8f055bd62a02677b
mailtrap.inbox.id=4631632

spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=587
spring.mail.username=0c8986927ca5ff
spring.mail.password=d3962daf34e7f4
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.ssl.enable=false
spring.mail.properties.mail.debug=true
app.mail.from=${MAIL_FROM:info@timescope.org}
spring.mail.default-encoding=UTF-8