spring.application.name=timescope
server.port=${PORT:8080}
api.version=${API_VERSION:v1}

spring.web.error.include-message=always

## Base de datos de desarrollo puede ser H2
#spring.datasource.password=password
# http://localhost:8080/h2-console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.url=jdbc:h2:mem:timescope
spring.datasource.username=sa
spring.h2.console.settings.web-allow-others=false
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

## Carga de Base de Datos
spring.jpa.defer-datasource-initialization=true
spring.jpa.hibernate.ddl-auto=create-drop
spring.sql.init.mode=always
logging.level.org.hibernate.orm.jdbc.bind=TRACE

## SQL
spring.jpa.show-sql=true

## JWT
jwt.secret=SoloEstasYSoloAprendisteAEstarPorVivirConMiedoAVolverAmarOjalaTeQuieranComoQuisiste
jwt.expiration=86400

#Email

spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=2525
spring.mail.username=5f57559dcaa97d
spring.mail.password=45c18abbc6a72d
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.ssl.enable=false
spring.mail.properties.mail.debug=true
app.mail.from={MAIL_FROM:pruebapruebasdaw2026@gmail.com}