### Proceso de Login - María Martínez
POST http://localhost:8080/api/v1/auth/signin
Content-Type: application/json

{
  "username": "mmartinez",
  "password": "MartinezMartinez"
}

> {% client.global.set("auth_token", response.body.token); %}

### Protocolo para cambiar de contraseña
PATCH http://localhost:8080/api/v1/auth/password
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
    "password": "MartinezMartinez",
    "newPassword": "Hola12345",
    "passwordComprobacion": "Hola12345"
}

###