### GET ALL - Obtener todos los proyectos (paginado)
### Requiere rol: director Y supervisor
GET http://localhost:8080/api/v1/proyectos
    ?page=0
    &size=10
    &sortBy=id
    &direction=asc
Authorization: Bearer {{auth_token}}

### GET ALL - Filtrar por nombre
GET http://localhost:8080/api/v1/proyectos
    ?nombre=TimeScope
    &page=0
    &size=10
    &sortBy=id
    &direction=asc
Authorization: Bearer {{auth_token}}

### GET ALL - Filtrar por estado isDeleted
GET http://localhost:8080/api/v1/proyectos
    ?isDeleted=false
    &page=0
    &size=10
Authorization: Bearer {{auth_token}}

### GET ALL - Filtrar por id
GET http://localhost:8080/api/v1/proyectos
    ?id=1
Authorization: Bearer {{auth_token}}

### PUT - AddUser
PUT http://localhost:8080/api/v1/proyectos/usuario/4?username=cgarcia
Content-Type: application/json
Authorization: Bearer {{auth_token}}