### Requiere rol: director
GET http://localhost:8080/api/v1/usuarios
    ?page=0
    &size=10
    &sortBy=id
    &direction=asc
Authorization: Bearer {{auth_token}}

### GET ALL - Filtrar por username
GET http://localhost:8080/api/v1/usuarios
    ?username=mmartinez
    &page=0
    &size=10
Authorization: Bearer {{auth_token}}

### GET ALL - Filtrar por email
GET http://localhost:8080/api/v1/usuarios
    ?email=juan.perez@timescope.es
    &page=0
    &size=10
Authorization: Bearer {{auth_token}}

###

### GET ALL - Filtrar por isDeleted
GET http://localhost:8080/api/v1/usuarios
    ?isDeleted=false
    &page=0
    &size=10
Authorization: Bearer {{auth_token}}

### GET ALL - Filtrar por username e isDeleted
GET http://localhost:8080/api/v1/usuarios
    ?username=alopez
    &isDeleted=false
    &page=0
    &size=10
    &sortBy=id
    &direction=desc
Authorization: Bearer {{auth_token}}

### PATCH - Asignar rol a un usuario - requiere rol: DIRECTOR y COORDINADOR

PATCH http://localhost:8080/api/v1/usuarios/1/asingRol?role=COORDINADOR
Authorization: Bearer {{auth_token}}

### POST - Crear Usuarios
POST http://localhost:8080/api/v1/usuarios
Content-Type: application/json

{
 "nombres": "Juan Jesus Sebastian",
 "apellidos": "Trejo Salinas",
 "email": "juanjesustrejosalinas06@gmail.com",
 "username": "jjsts06",
  "password": "kknero"
}
